## note on numpy reference pdf 1.23.0

### 结合 array 的方法

#### concatenate

In [6]:
import numpy as np
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])
np.concatenate((a, b), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

#### stack

In [20]:
import numpy as np
a = np.array([1, 2, 3])
print(a)
b = np.array([4, 5, 6])
print(b)
print(np.stack((a, b)))
print(np.hstack((a, b)))
print(np.vstack((a, b)))

[1 2 3]
[4 5 6]
[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]
